import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// All words are exactly 5 lowercase letters [a-z], no accents, no proper nouns.
// A runtime filter is applied before insertion as a safety net.
const words: string[] = [
  // --- Pronomes / determinantes / advérbios ---
  'outra', 'outro', 'nossa', 'nosso', 'vossa', 'vosso', 'todas', 'todos',
  'algum', 'muito', 'pouco', 'tanto', 'tanta', 'mesmo', 'mesma', 'ambos',
  'ambas', 'certo', 'certa', 'entre', 'sobre', 'ainda', 'agora', 'antes',
  'desde', 'nunca', 'quase', 'acima', 'junto', 'quais', 'certo', 'longe',
  'perto', 'jamais', 'abaixo', 'dentre', 'aonde', 'donde', 'aquem',
  'alem', 'afora', 'apos', 'circa', 'alias', 'porem', 'senam', 'senao',
  'quase', 'talvez', 'alias', 'mesmo', 'avante', 'atras', 'junta', 'juntos',
  'torno', 'volta', 'enfim', 'alias', 'certo', 'nisto', 'nisso', 'nesse',
  'nessa', 'neste', 'nesta', 'neles', 'nelas', 'neles', 'deles', 'delas',
  'deste', 'desta', 'desse', 'dessa', 'daqui', 'dali', 'disso', 'disto',
  'aqui', 'quem', 'qual', 'cujo', 'cuja', 'onde', 'logo', 'logo',

  // --- Verbos no infinitivo (5 letras) ---
  'comer', 'beber', 'fazer', 'poder', 'dizer', 'viver', 'saber', 'levar',
  'valer', 'criar', 'achar', 'andar', 'passar', 'ficar', 'estar', 'bater',
  'correr', 'falar', 'jogar', 'rolar', 'rezar', 'pagar', 'morar', 'votar',
  'nadar', 'olhar', 'casar', 'parar', 'tirar', 'tocar', 'voar', 'girar',
  'secar', 'lavar', 'lutar', 'pular', 'gritar', 'chorar', 'ouvir', 'subir',
  'cavar', 'unir', 'ferir', 'pedir', 'servir', 'medir', 'ceder', 'vender',
  'matar', 'trazer', 'mentir', 'sentir', 'dormir', 'mexer', 'varrer',
  'sofrer', 'fritar', 'assar', 'cozer', 'gelar', 'fumar', 'sujar', 'morder',
  'cortar', 'colar', 'pesar', 'mover', 'vencer', 'erguer', 'tecer', 'urdir',
  'coser', 'ceder', 'amar', 'usufruir', 'poupar', 'contar', 'cantar',
  'roubar', 'nasce', 'casar', 'chamar', 'entrar', 'somar', 'ajudar',
  'ligar', 'seguir', 'mudar', 'voar', 'girar', 'testar', 'notar', 'tentar',
  'errar', 'saltar', 'amar', 'abrir', 'selar', 'checar', 'varar', 'surtar',
  'urrar', 'fartar', 'velar', 'zelar', 'trair', 'fugir', 'cair', 'rir',
  'ir', 'pôr', 'orar', 'arder', 'gemir', 'latir', 'rugir', 'gemer',
  'sugar', 'chupar', 'lamber', 'cheirar', 'tentar', 'aceitar', 'negar',
  'afirmar', 'crer', 'temer', 'odiar', 'amar', 'querer', 'poder',
  'dever', 'haver', 'sorrir', 'chorar', 'rir', 'amar',

  // --- Verbos conjugados comuns (5 letras) ---
  'tenho', 'quero', 'posso', 'farei', 'fazes', 'fazem', 'sabem', 'sabes',
  'sabia', 'tinha', 'seria', 'fosse', 'estou', 'estas', 'somos', 'serei',
  'vamos', 'vende', 'venho', 'venha', 'virei', 'viria', 'viram', 'foram',
  'forem', 'fique', 'ficou', 'ficam', 'passa', 'perco', 'levou', 'levam',
  'trago', 'adora', 'adoro', 'ajuda', 'ajudo', 'aluga', 'alugo', 'acha',
  'acho', 'acham', 'anda', 'ando', 'andam', 'basta', 'canta', 'canto',
  'chama', 'chamo', 'chega', 'chego', 'come', 'como', 'corre', 'corro',
  'conta', 'conto', 'corta', 'entra', 'entro', 'fecha', 'fecho', 'fala',
  'falo', 'falam', 'ganha', 'ganho', 'gosta', 'gosto', 'joga', 'jogo',
  'leva', 'levo', 'liga', 'ligo', 'mora', 'moro', 'muda', 'mudo',
  'nada', 'nado', 'olha', 'olho', 'paga', 'pago', 'para', 'paro',
  'perde', 'pensa', 'penso', 'pula', 'pulo', 'sabe', 'sai', 'saio',
  'sente', 'sinto', 'serve', 'sirvo', 'toca', 'toco', 'toma', 'tomo',
  'torna', 'usa', 'uso', 'usam', 'viro', 'vive', 'vivo', 'vivem',
  'voa', 'volta', 'volto', 'disse', 'dizia', 'desce', 'danca',
  'salta', 'salto', 'grita', 'grito', 'chora', 'choro', 'corre',
  'foge', 'fugio', 'surgiu', 'sumiu', 'caiu', 'cair', 'caem', 'sobe',
  'sobem', 'veio', 'vejo', 'nasce', 'cresce', 'morre', 'morro', 'morrem',
  'viveu', 'nasceu', 'cresceu', 'morreu', 'cantou', 'chorou', 'lutou',
  'ganhou', 'perdeu', 'comprou', 'vendeu', 'pagou', 'levou', 'trouxe',
  'disse', 'fez', 'foi', 'deu', 'veio', 'pôs', 'soube', 'quis',
  'pude', 'disse', 'viu', 'ouvi', 'ouvi', 'saiu', 'entrou', 'ficou',
  'partiu', 'chegou', 'voltou', 'mudou', 'parou', 'criou', 'abriu',
  'fechou', 'ligou', 'desligou', 'cortou', 'bateu', 'caiu', 'subiu',
  'desceu', 'correu', 'pulou', 'saltou', 'voou', 'nadou',

  // --- Natureza (5 letras) ---
  'terra', 'pedra', 'folha', 'campo', 'monte', 'vento', 'chuva', 'neve',
  'gelo', 'fogo', 'agua', 'clima', 'calor', 'sombra', 'noite', 'tarde',
  'manha', 'prado', 'selva', 'mato', 'erva', 'tronco', 'ramo', 'vapor',
  'bruma', 'lama', 'barro', 'onda', 'tocha', 'astro', 'arena', 'areia',
  'dunas', 'farol', 'coral', 'mangue', 'cerrado', 'pampa', 'brisa',
  'nuvem', 'raio', 'trovo', 'granizo', 'geada', 'orvalho', 'lagoa',
  'arroio', 'regato', 'riacho', 'fonte', 'poço', 'cisterna', 'reserva',
  'ilhota', 'ilheu', 'atol', 'recife', 'baixio', 'escolho', 'rochedo',
  'penedo', 'morro', 'colina', 'planalto', 'planicie', 'vale', 'desfiladeiro',
  'floresta', 'caatinga', 'cerrado', 'pantanal', 'restinga', 'tabuleiro',
  'serrado', 'chapadao', 'chapada', 'encosta', 'vertente', 'encosta',
  'praia', 'costa', 'litoral', 'golfao', 'enseada', 'baia', 'estreito',
  'canal', 'delta', 'estuario', 'mangue', 'igapo', 'igarape', 'caapora',
  'louro', 'cedro', 'pinho', 'abeto', 'cipre', 'ficus', 'samambaia',
  'musgo', 'liquen', 'cacto', 'palma', 'bambu', 'cana', 'junco', 'taboa',
  'alga', 'coral', 'esponja', 'medusa', 'polipo', 'crinoide',
  'safira', 'rubi', 'esmeralda', 'topazio', 'quartzo', 'granito',
  'basalto', 'ardosia', 'arenito', 'calcario', 'marmore', 'xisto',

  // --- Animais (5 letras) ---
  'cobra', 'leao', 'tigre', 'urso', 'lobo', 'veado', 'macaco', 'jacare',
  'lagarto', 'sapo', 'polvo', 'abelha', 'aranha', 'grilo', 'pombo', 'corvo',
  'falcao', 'gatos', 'patos', 'bode', 'boi', 'burro', 'porco', 'ovelha',
  'cabra', 'jegue', 'asno', 'mulo', 'mula', 'cervo', 'javali', 'raposa',
  'texugo', 'quati', 'cutia', 'paca', 'capivara', 'irara', 'furão',
  'lontra', 'nutria', 'castor', 'rato', 'ratao', 'camundongo', 'hamster',
  'esquilo', 'marmota', 'preá', 'mocó', 'coelho', 'lebre',
  'morcego', 'tamanduá', 'preguiça', 'tatu', 'tatuzinho', 'gambá',
  'jaguara', 'onça', 'puma', 'suçuarana', 'guepardo', 'leopardo',
  'leopardo', 'hiena', 'chacal', 'coiote', 'dingo', 'alce',
  'bisão', 'bisonte', 'bufalo', 'zebra', 'antilope', 'gnu', 'impala',
  'girafas', 'elefante', 'rinoceronte', 'hipopotamo',
  'chimpanze', 'gorila', 'orangotango', 'macaco', 'babuino',
  'pinguim', 'flamingo', 'avestruz', 'emu', 'tucano', 'arara',
  'papagaio', 'calopsita', 'canario', 'rouxinol', 'sabia', 'bem-te-vi',
  'andorinha', 'pomba', 'codorniz', 'faisao', 'peru', 'pato', 'ganso',
  'cisne', 'garça', 'socó', 'beija-flor', 'martim-pescador',
  'coruja', 'mocho', 'gaviao', 'aguia', 'abutre', 'urubu',
  'peixe', 'atum', 'salmao', 'truta', 'tilapia', 'corvina', 'robalo',
  'anchova', 'sardinha', 'bacalhau', 'linguado', 'badejo', 'cherne',
  'pirarucu', 'tucunare', 'curimba', 'dourado', 'surubim',
  'arraia', 'tubarao', 'golfinho', 'baleia', 'dugongo', 'lamantim',
  'foca', 'morsa', 'leao-marinho', 'polvinho', 'polvo', 'lula',
  'carangueijo', 'lagosta', 'camarao', 'siris', 'siri', 'caranguejo',
  'mexilhao', 'ostra', 'marisco', 'vieira', 'berbigao',
  'borboleta', 'mariposa', 'abelha', 'vespa', 'marimbondo', 'besouro',
  'joaninha', 'louva-a-deus', 'libélula', 'mosca', 'mosquito',
  'formiga', 'cupim', 'barata', 'percevejo', 'pulgao', 'traca',
  'minhoca', 'lesma', 'caracol', 'escargot', 'centopeia', 'milipede',

  // --- Corpo humano (5 letras) ---
  'braco', 'perna', 'dente', 'sangue', 'nervo', 'pele', 'barba',
  'olhos', 'labio', 'garganta', 'ombro', 'pulso', 'palma', 'dedos',
  'unhas', 'peito', 'costas', 'nuca', 'testa', 'queixo', 'cilio',
  'pupila', 'veia', 'ossos', 'musculo', 'coluna', 'costela',
  'cotovelo', 'joelho', 'calcanhar', 'tornozelo', 'quadril', 'cintura',
  'barriga', 'umbigo', 'coxas', 'pescoco', 'bochecha', 'sobrancelha',
  'cabelo', 'nariz', 'boca', 'lingua', 'orelha', 'ouvido',
  'figado', 'rins', 'bexiga', 'estomago', 'intestino', 'pancreas',
  'cerebro', 'medula', 'pulmo', 'coracao', 'arteria', 'tendao',

  // --- Casa e objetos domésticos (5 letras) ---
  'porta', 'janela', 'parede', 'teto', 'chao', 'quarto', 'sala',
  'varanda', 'jardim', 'quintal', 'cerca', 'muro', 'prato', 'colher',
  'garfo', 'panela', 'toalha', 'pano', 'balde', 'escova', 'esponja',
  'lixo', 'lata', 'jarra', 'caixa', 'saco', 'bolsa', 'mala', 'chave',
  'botao', 'tomada', 'lampada', 'vela', 'forno', 'forma', 'grade',
  'telha', 'tijolo', 'calha', 'goteira', 'tubulacao', 'cano', 'ralo',
  'gaveta', 'armario', 'prateleira', 'gancho', 'pregao', 'preguinho',
  'tapete', 'almofada', 'travesseiro', 'coberta', 'edredon', 'fronha',
  'lencol', 'cobertor', 'manta', 'colcha', 'espelho', 'moldura',
  'quadro', 'vaso', 'floreira', 'cachepot', 'pendente', 'abajur',
  'cortina', 'persiana', 'veneziana', 'anteparo', 'biombo', 'divisoria',
  'mesa', 'cadeira', 'sofa', 'poltrona', 'banqueta', 'taburete',
  'escrivaninha', 'aparador', 'cristaleira', 'estante', 'livreiro',
  'escada', 'corrimao', 'degrau', 'lance', 'patamar', 'elevador',
  'portao', 'campainha', 'interfone', 'citofone', 'trinco', 'ferrolho',
  'tranca', 'corrente', 'cadeado', 'fechadura', 'chave',
  'vassoura', 'espanador', 'rodo', 'esfregao', 'aspirador',
  'ferro', 'tabua', 'cabide', 'cabideiro', 'pendurador',
  'frigideira', 'chaleira', 'leiteira', 'tampa', 'refri', 'geladeira',
  'freezer', 'microondas', 'torradeira', 'cafeteira', 'filtro', 'coador',
  'assadeira', 'tabuleiro', 'panelinha', 'caneco', 'xicara', 'caneca',
  'copo', 'taca', 'garrafa', 'termos', 'garrafa', 'squeeze',
  'saladeira', 'tigela', 'travessa', 'sopeira', 'molheira',

  // --- Alimentos (5 letras) ---
  'arroz', 'milho', 'trigo', 'aveia', 'cevada', 'centeio', 'pao',
  'bolo', 'torta', 'doce', 'mel', 'acucar', 'sal', 'pimenta', 'alho',
  'cebola', 'tomate', 'batata', 'cenoura', 'beterraba', 'pepino',
  'alface', 'repolho', 'couve', 'ervilha', 'feijao', 'lentilha', 'grao',
  'soja', 'amendoim', 'castanha', 'ameixa', 'uva', 'pera', 'maca',
  'pessego', 'cereja', 'morango', 'caju', 'goiaba', 'manga', 'mamao',
  'coco', 'banana', 'laranja', 'limao', 'abacate', 'kiwi', 'figo',
  'melao', 'carne', 'frango', 'ovo', 'leite', 'queijo', 'manteiga',
  'nata', 'creme', 'presunto', 'bacon', 'azeite', 'oleo', 'vinagre',
  'molho', 'caldo', 'sopa', 'salada', 'cafe', 'cha', 'suco', 'vinho',
  'cerveja', 'pizza', 'lanche', 'crepe', 'waffle', 'panqueca', 'omelete',
  'risoto', 'massa', 'ravioli', 'nhoque', 'polenta', 'fuba', 'amido',
  'farinha', 'fermento', 'bicarbonato', 'sal', 'pimentao', 'urucum',
  'colorau', 'cominho', 'oregano', 'manjericao', 'alecrim', 'tomilho',
  'louro', 'coentro', 'salsa', 'cebolinha', 'hortelã', 'erva-doce',
  'canela', 'cravo', 'noz-moscada', 'cardamomo', 'acafrao', 'curry',
  'gengibre', 'wasabi', 'pimenta-do-reino', 'malagueta', 'tabasco',
  'ketchup', 'mostarda', 'maionese', 'relish', 'chutney', 'pesto',
  'hummus', 'tahine', 'guacamole', 'bruschetta', 'gazpacho', 'ratatouille',
  'paella', 'sushi', 'sashimi', 'temaki', 'uramaki', 'gyoza', 'ramen',
  'pho', 'curry', 'biryani', 'kebab', 'falafel', 'shawarma', 'tacos',
  'burrito', 'quesadilla', 'guacamole', 'salsa', 'nachos', 'empanada',
  'brigadeiro', 'beijinho', 'cajuzinho', 'cocada', 'paçoca', 'pe-de-moleque',
  'goiabada', 'marmelada', 'geleia', 'doce-de-leite', 'pudim',
  'mousse', 'panna-cotta', 'tiramisu', 'cheesecake', 'brownie',
  'cookie', 'macaron', 'profiterole', 'eclair', 'croissant', 'brioche',

  // --- Vestuário (5 letras) ---
  'camisa', 'blusa', 'casaco', 'jaqueta', 'colete', 'gravata', 'colar',
  'brinco', 'anel', 'pulseira', 'chapeu', 'bone', 'gorro', 'luvas',
  'meias', 'cueca', 'cinto', 'pijama', 'bermuda', 'saia', 'vestido',
  'calca', 'terno', 'farda', 'avental', 'bata', 'jaleco', 'sapato',
  'tenis', 'bota', 'sandalia', 'chinelo', 'solado', 'sueter', 'moletom',
  'canga', 'pareo', 'lenco', 'cachecol', 'echarpe', 'meia', 'legging',
  'macacao', 'jardineira', 'macacao', 'sarro', 'polo', 'regata',
  'camiseta', 'camisola', 'roupao', 'biquini', 'maio', 'shorts',
  'calcinha', 'sutia', 'corselet', 'espartilho', 'corpete', 'faixa',
  'torcida', 'tiara', 'hairband', 'presilha', 'grampo', 'piranha',
  'bracelete', 'tornozeleira', 'colar', 'berloque', 'pingente',
  'broche', 'alfinete', 'botao', 'zipper', 'fivela', 'colchete',
  'ilho', 'cadarco', 'velcro', 'elastico', 'bordado', 'renda', 'franja',
  'estampa', 'listra', 'xadrez', 'poá', 'floral', 'animal-print',
  'jeans', 'couro', 'camurca', 'veludo', 'seda', 'linho', 'algodao',
  'poliester', 'nylon', 'viscose', 'acrilico', 'la', 'cashmere', 'lycra',

  // --- Transporte (5 letras) ---
  'carro', 'moto', 'onibus', 'caminhao', 'taxi', 'metro', 'trem',
  'aviao', 'barco', 'navio', 'canoa', 'lancha', 'bicicleta', 'skate',
  'estrada', 'rua', 'avenida', 'ponte', 'tunel', 'cais', 'porto',
  'garagem', 'posto', 'caminhonete', 'van', 'jeep', 'fusca', 'kombi',
  'triciclo', 'reboque', 'trailer', 'ambulancia', 'viatura', 'guindaste',
  'trator', 'colheitadeira', 'escavadeira', 'retroescavadeira', 'grua',
  'andaime', 'betoneira', 'compactador', 'rolo', 'niveladora',
  'motocicleta', 'scooter', 'ciclomotor', 'moped', 'bicicleta',
  'velocipede', 'monociclo', 'patins', 'patinete', 'hoverboard',
  'monotrim', 'segway', 'cadeira-de-rodas', 'andador', 'muleta',
  'pena', 'asa-delta', 'parapente', 'balao', 'zeppelin', 'dirigivel',
  'ultraleve', 'planador', 'paraquedas', 'jetpack', 'foguete', 'onibus-espacial',
  'remo', 'pagaia', 'vela', 'motor', 'helice', 'leme', 'ancora', 'proa',
  'popa', 'estibordo', 'bombordo', 'mastro', 'vela', 'quilha', 'casco',

  // --- Tecnologia (5 letras) ---
  'celular', 'tablet', 'laptop', 'monitor', 'teclado', 'camera',
  'radio', 'controle', 'cabo', 'bateria', 'antena', 'sinal', 'rede',
  'arquivo', 'pasta', 'email', 'senha', 'usuario', 'conta', 'login',
  'acesso', 'dados', 'nuvem', 'servidor', 'banco', 'codigo', 'erro',
  'pixel', 'tela', 'cursor', 'janela', 'botao', 'link', 'mapa', 'site',
  'app', 'blog', 'forum', 'chat', 'video', 'audio', 'stream', 'upload',
  'download', 'backup', 'cache', 'cookie', 'token', 'hash', 'cript',
  'sensor', 'chip', 'placa', 'disco', 'ssd', 'hdd', 'ram', 'cpu',
  'gpu', 'bios', 'firmware', 'driver', 'kernel', 'shell', 'bash',
  'python', 'java', 'csharp', 'ruby', 'swift', 'kotlin', 'rust', 'go',
  'html', 'css', 'json', 'xml', 'sql', 'api', 'sdk', 'ide', 'git',
  'agile', 'scrum', 'devops', 'docker', 'nuvem', 'lambda', 'cicd',
  'robot', 'drone', 'ia', 'ml', 'dl', 'rede', 'neural', 'dados',
  'bigdata', 'blockchain', 'nft', 'crypto', 'bitcoin', 'altcoin',
  'token', 'wallet', 'exchange', 'fintech', 'startup', 'unicornio',

  // --- Trabalho e profissões (5 letras) ---
  'medico', 'dentista', 'diretor', 'gerente', 'advogado', 'juiz',
  'policial', 'bombeiro', 'piloto', 'motorista', 'taxista', 'vendedor',
  'garcom', 'padeiro', 'pedreiro', 'pintor', 'mecanico', 'musico',
  'cantor', 'atleta', 'tecnico', 'padre', 'pastor', 'zelador', 'fiscal',
  'auditor', 'contador', 'analista', 'enfermeiro', 'veterinario',
  'professor', 'aluno', 'secretario', 'engenheiro', 'arquiteto',
  'militar', 'comerciante', 'caixa', 'atendente', 'cozinheiro',
  'confeiteiro', 'acougueiro', 'peixeiro', 'carpinteiro', 'eletricista',
  'encanador', 'soldador', 'costureira', 'cabeleireiro', 'barbeiro',
  'fotografo', 'jornalista', 'escritor', 'ator', 'dançarino',
  'treinador', 'rabino', 'monge', 'freira', 'faxineiro', 'jardineiro',
  'porteiro', 'segurança', 'economista',

  // --- Escola e educação (5 letras) ---
  'escola', 'sala', 'turma', 'aula', 'prova', 'teste', 'nota',
  'livro', 'caderno', 'caneta', 'lapis', 'borracha', 'papel', 'pincel',
  'tinta', 'quadro', 'lousa', 'giz', 'mapa', 'globo',

  // --- Saúde e medicina (5 letras) ---
  'saude', 'remedio', 'vacina', 'dose', 'agulha', 'curativo', 'receita',
  'terapia', 'hospital', 'clinica', 'farmacia', 'alergia', 'gripe',
  'febre', 'tosse', 'enjoo', 'depressao', 'ansiedade', 'panico',
  'fobia', 'estresse', 'insonia',

  // --- Família e relações (5 letras) ---
  'filho', 'filha', 'neto', 'neta', 'tio', 'tia', 'primo', 'prima',
  'sobrinho', 'sobrinha', 'cunhado', 'cunhada', 'sogro', 'sogra',
  'genro', 'nora', 'marido', 'esposa', 'noivo', 'noiva', 'amigo',
  'amiga', 'colega', 'vizinho', 'vizinha', 'parceiro', 'parceira', 'chefe',

  // --- Lugares (5 letras) ---
  'cidade', 'estado', 'bairro', 'vila', 'praca', 'parque', 'mercado',
  'feira', 'loja', 'museu', 'galeria', 'teatro', 'cinema', 'estadio',
  'ginasio', 'academia', 'clube', 'prefeitura', 'camara', 'senado',
  'tribunal', 'delegacia', 'quartel', 'fabrica', 'usina', 'fazenda',
  'sitio', 'rancho', 'granja', 'hotel', 'pousada', 'hostel', 'motel',
  'resort', 'camping', 'restaurante', 'bar', 'boate', 'festa', 'salao',
  'templo', 'igreja', 'catedral', 'convento', 'mosteiro',

  // --- Adjetivos (5 letras) ---
  'outra', 'outro', 'lindo', 'linda', 'bonito', 'bonita', 'belo', 'bela',
  'alto', 'alta', 'baixo', 'baixa', 'gordo', 'gorda', 'magro', 'magra',
  'forte', 'fraco', 'fraca', 'lento', 'lenta', 'duro', 'dura',
  'macio', 'macia', 'suave', 'liso', 'lisa', 'largo', 'larga',
  'curto', 'curta', 'grosso', 'grossa', 'fino', 'fina',
  'cheio', 'cheia', 'vazio', 'vazia', 'limpo', 'limpa', 'sujo', 'suja',
  'novo', 'nova', 'velho', 'velha', 'jovem', 'rico', 'rica', 'pobre',
  'livre', 'preso', 'presa', 'aberto', 'aberta', 'fechado', 'fechada',
  'quente', 'morno', 'morna', 'gelado', 'gelada', 'seco', 'seca',
  'molhado', 'molhada', 'fresco', 'fresca', 'maduro', 'madura', 'verde',
  'cru', 'crua', 'podre', 'doce', 'amargo', 'amarga', 'azedo', 'azeda',
  'salgado', 'salgada', 'claro', 'clara', 'escuro', 'escura',
  'feliz', 'triste', 'alegre', 'calmo', 'calma', 'nervoso', 'nervosa',
  'cansado', 'cansada', 'ativo', 'ativa', 'burro', 'burra',
  'esperto', 'esperta', 'sabio', 'sabia', 'curioso', 'curiosa',
  'corajoso', 'covarde', 'honesto', 'honesta', 'leal', 'generoso',
  'generosa', 'egoista', 'gentil', 'educado', 'educada', 'hostil',
  'amavel', 'amoroso', 'carinhoso', 'paciente', 'tolerante',
  'rigido', 'rigida', 'teimoso', 'teimosa', 'confiante', 'timido',
  'timida', 'simples', 'facil', 'certo', 'errado', 'correto',
  'falso', 'falsa', 'real', 'urgente', 'util', 'inutil', 'eficaz',
  'adequado', 'suficiente', 'escasso', 'raro', 'rara', 'comum',
  'especial', 'unico', 'unica', 'igual', 'diferente', 'parecido',
  'oposto', 'oposta', 'positivo', 'positiva', 'negativo', 'negativa',
  'neutro', 'neutra',

  // --- Substantivos gerais (5 letras exactas) ---
  'tempo', 'mundo', 'vida', 'parte', 'grupo', 'ponto', 'lugar', 'coisa',
  'gente', 'modo', 'tipo', 'lado', 'linha', 'base', 'grau', 'valor',
  'preco', 'custo', 'gasto', 'lucro', 'ganho', 'perda', 'risco',
  'sorte', 'azar', 'inicio', 'etapa', 'fase', 'passo', 'acao',
  'efeito', 'causa', 'razao', 'motivo', 'meta', 'alvo', 'plano',
  'ideia', 'evento', 'fato', 'dado', 'numero', 'total', 'media',
  'soma', 'produto', 'resultado', 'resposta', 'pergunta', 'duvida',
  'opiniao', 'pedido', 'ordem', 'regra', 'lei', 'norma', 'padrao',
  'modelo', 'exemplo', 'prova', 'acordo', 'promessa', 'mentira',
  'verdade', 'segredo', 'noticia', 'boato', 'fama', 'marca', 'nome',
  'titulo', 'cargo', 'papel', 'tarefa', 'missao', 'dever', 'direito',
  'forca', 'energia', 'vontade', 'desejo', 'sonho', 'medo', 'coragem',
  'amor', 'odio', 'raiva', 'alegria', 'tristeza', 'saudade', 'orgulho',
  'vergonha', 'culpa', 'perdao', 'gratidao', 'respeito', 'confianca',
  'alma', 'mente', 'pensamento', 'memoria', 'realidade', 'fantasia',
  'talento', 'vocacao', 'paixao', 'interesse', 'lazer', 'esporte',
  'cultura', 'arte', 'musica', 'teatro', 'cinema', 'literatura',
  'poesia', 'conto', 'romance', 'ciencia', 'tecnologia', 'negocio',
  'empresa', 'mercado', 'economia', 'politica', 'governo', 'sociedade',
  'comunidade', 'equipe', 'nacao', 'tradicao', 'costume', 'habito',
  'rotina', 'mudanca', 'reforma', 'crise', 'problema', 'desafio',
  'solucao', 'opcao', 'escolha', 'decisao', 'avaliacao', 'analise',

  // === Lote de 5 letras exatas — curado manualmente ===
  'abade', 'abalo', 'abana', 'abate', 'abeto', 'abono', 'abril', 'abuso',
  'acaba', 'acabe', 'acabo', 'acalo', 'acama', 'acara', 'acaso', 'acata',
  'acato', 'acede', 'aceno', 'acesa', 'aceso', 'acido', 'acima', 'acode',
  'adaga', 'adega', 'adere', 'adeus', 'afago', 'afeto', 'afiam', 'afiar',
  'afina', 'afino', 'afoga', 'afogo', 'agito', 'agudo', 'ajuda', 'ajudo',
  'alada', 'alado', 'alaga', 'alago', 'algum', 'aliar', 'alija', 'alijo',
  'aliso', 'aloja', 'alojo', 'aluno', 'amado', 'amaga', 'amago', 'amara',
  'amaro', 'amasa', 'amaso', 'amata', 'amato', 'ameno', 'amigo', 'amora',
  'amoro', 'amplo', 'anela', 'anelo', 'anima', 'animo', 'anota', 'anoto',
  'antro', 'apara', 'aparo', 'apelo', 'apito', 'apoia', 'apoio', 'apura',
  'apuro', 'ardor', 'ardua', 'arduo', 'areja', 'arejo', 'arena', 'arido',
  'arroz', 'astro', 'atola', 'atolo', 'atona', 'atono', 'atlas', 'avara',
  'avaro', 'avena', 'aviso', 'aviva', 'avivo', 'azeda', 'azedo', 'babar',
  'babau', 'bagre', 'baile', 'baixa', 'baixo', 'baldo', 'balsa', 'banco',
  'banda', 'banha', 'banho', 'baque', 'barca', 'bardo', 'barao', 'barra',
  'barro', 'basta', 'basto', 'batom', 'beira', 'belas', 'belos', 'beijo',
  'berco', 'berma', 'besta', 'bingo', 'bioma', 'birra', 'bispo', 'bicho',
  'bilha', 'bloco', 'bocal', 'bolar', 'bolsa', 'bonde', 'bonus', 'borda',
  'bordo', 'botao', 'braco', 'brasa', 'bravo', 'breve', 'briga', 'brisa',
  'brito', 'broto', 'bruma', 'bucho', 'burla', 'burlo', 'burra', 'burro',
  'busca', 'busco', 'cabra', 'cacau', 'cacos', 'calar', 'calca', 'calco',
  'caldo', 'calha', 'canca', 'canga', 'canto', 'carao', 'cargo', 'caris',
  'carma', 'carne', 'carpe', 'carpo', 'cassa', 'casso', 'causa', 'causo',
  'cavar', 'ceara', 'cerco', 'cerra', 'chaga', 'chale', 'chama', 'chamo',
  'chapa', 'chapo', 'chave', 'chefa', 'chefo', 'chiar', 'chile', 'choca',
  'choco', 'choro', 'ciano', 'ciclo', 'cinco', 'cinza', 'circo', 'cirro',
  'civel', 'clero', 'clone', 'clube', 'cocar', 'cocho', 'coeso', 'coima',
  'coimo', 'coito', 'colmo', 'colos', 'combo', 'comum', 'conde', 'cones',
  'copos', 'coque', 'corda', 'coroa', 'corpo', 'corsa', 'corso', 'corta',
  'corte', 'costa', 'cotas', 'couro', 'covas', 'cravo', 'crime', 'crise',
  'cruel', 'cueca', 'culpa', 'culpo', 'cunha', 'cunho', 'curso', 'curva',
  'curvo', 'dance', 'danta', 'danto', 'darei', 'deite', 'delta', 'dengo',
  'denso', 'desar', 'diabo', 'dieta', 'dingo', 'disco', 'doado', 'dobra',
  'dobro', 'doido', 'dolar', 'dolce', 'domea', 'dorso', 'drone', 'droga',
  'duplo', 'duque', 'duras', 'duros', 'educa', 'educo', 'elege', 'elejo',
  'eleva', 'elevo', 'emana', 'emano', 'emite', 'emito', 'envia', 'envio',
  'ereto', 'erode', 'erodo', 'eroga', 'erogo', 'escoa', 'escoo', 'espia',
  'espio', 'etapa', 'etnia', 'evade', 'evado', 'evita', 'evito', 'exala',
  'exalo', 'exame', 'exata', 'exato', 'exibe', 'exibo', 'exige', 'exijo',
  'exila', 'exilo', 'exime', 'eximo', 'facao', 'falca', 'falco', 'farsa',
  'favor', 'fazia', 'febre', 'fecho', 'feira', 'feito', 'feliz', 'ferra',
  'ferro', 'festa', 'finca', 'fixar', 'fogar', 'foice', 'folar', 'forja',
  'forjo', 'forno', 'forra', 'forro', 'fosco', 'frade', 'fraga', 'frase',
  'frear', 'freia', 'freio', 'frevo', 'frios', 'friso', 'fugaz', 'fungo',
  'furia', 'furta', 'furto', 'gabao', 'gabar', 'galga', 'galgo', 'galha',
  'galho', 'garoa', 'gasta', 'gasto', 'gelar', 'genio', 'gemir', 'gleba',
  'glosa', 'gloso', 'golas', 'golpe', 'gordo', 'gorja', 'gorro', 'gozar',
  'grade', 'grafo', 'grama', 'grana', 'grave', 'greve', 'grilo', 'gripe',
  'grota', 'herda', 'herdo', 'heroi', 'hidra', 'hiena', 'icone', 'ideia',
  'idolo', 'ilude', 'iludo', 'imite', 'imito', 'inibe', 'inibo', 'isola',
  'isolo', 'joias', 'julga', 'julgo', 'junto', 'jurar', 'labor', 'ladro',
  'lagoa', 'laivo', 'lambe', 'lambo', 'lance', 'lanco', 'lapis', 'larga',
  'largo', 'laser', 'lasso', 'latir', 'lazao', 'lebre', 'legal', 'legar',
  'leite', 'lenha', 'lenho', 'lento', 'lesto', 'licor', 'limao', 'linfa',
  'litro', 'livre', 'lobos', 'longa', 'longo', 'lorca', 'magoa', 'magoo',
  'magra', 'magro', 'maior', 'males', 'mando', 'marao', 'mares', 'marna',
  'marno', 'massa', 'meada', 'meado', 'meiga', 'meigo', 'menor', 'metro',
  'milha', 'milho', 'minha', 'miude', 'miudo', 'modal', 'mogno', 'molde',
  'molho', 'moral', 'morca', 'morco', 'mordo', 'morsa', 'mosca', 'motim',
  'motor', 'mouro', 'multa', 'murro', 'musgo', 'nacao', 'naipe', 'naval',
  'negro', 'ninho', 'nitro', 'nivel', 'norma', 'novas', 'novos', 'nutro',
  'ocupa', 'odeia', 'odeio', 'ogiva', 'omega', 'optar', 'ostra', 'pacos',
  'padre', 'paira', 'pairo', 'palco', 'palha', 'palmo', 'palpo', 'papel',
  'papal', 'papai', 'papao', 'papos', 'parca', 'parco', 'patos', 'pavio',
  'pecar', 'pedal', 'pegue', 'penco', 'penha', 'penso', 'pesar', 'piada',
  'piano', 'picos', 'pilha', 'pilho', 'pinga', 'pingo', 'pisca', 'pisco',
  'pista', 'placa', 'plano', 'pluma', 'podar', 'polvo', 'pomba', 'pombo',
  'porca', 'porco', 'porao', 'potro', 'prado', 'prazo', 'preto', 'prima',
  'primo', 'prova', 'provo', 'pulso', 'purga', 'purgo', 'queda', 'racao',
  'radio', 'raiva', 'raivo', 'ralar', 'rampa', 'rapaz', 'rasga', 'rasgo',
  'raspa', 'raspo', 'rasto', 'remar', 'retro', 'rifar', 'rigor', 'rindo',
  'rocha', 'rodas', 'rolar', 'ronca', 'ronco', 'rosea', 'roseo', 'rosto',
  'rouco', 'rubro', 'rugir', 'ruido', 'ruivo', 'russo', 'sabor', 'sagaz',
  'sagra', 'sagro', 'salao', 'salga', 'salgo', 'salmo', 'salsa', 'salso',
  'salva', 'salvo', 'sarar', 'sarco', 'sauda', 'saude', 'saudo', 'sauna',
  'selva', 'senao', 'senha', 'sepia', 'serio', 'serra', 'serro', 'sigma',
  'signo', 'silvo', 'solar', 'solco', 'sorvo', 'sovao', 'sovar', 'sulco',
  'surdo', 'surja', 'surjo', 'surta', 'surto', 'susto', 'tacho', 'talco',
  'tapao', 'tapar', 'tapas', 'tarda', 'tarde', 'tardo', 'tarso', 'tecla',
  'teclo', 'telha', 'tendo', 'tenra', 'tenro', 'tenta', 'terco', 'termo',
  'terno', 'tersa', 'terso', 'tigre', 'tinto', 'tique', 'tirar', 'tiros',
  'toada', 'toldo', 'topar', 'topas', 'topos', 'toque', 'torpe', 'tosco',
  'tosse', 'tosso', 'touca', 'trair', 'trapo', 'travo', 'treco', 'trepa',
  'trepo', 'trevo', 'trica', 'trico', 'triga', 'trigo', 'trova', 'troxa',
  'truca', 'truco', 'tumor', 'turba', 'turco', 'turma', 'ungir', 'vagao',
  'vagar', 'vagas', 'valha', 'valor', 'valsa', 'varao', 'varoa', 'vedao',
  'vedar', 'velha', 'velho', 'veloz', 'venao', 'veras', 'versa', 'verso',
  'viela', 'vigor', 'visao', 'visor', 'vocal', 'vogal', 'xeque',

  // --- Lote extra para alcançar 2000 ---
  'abafa', 'abafo', 'abala', 'abale', 'abali', 'abase', 'abati', 'abduz',
  'abeia', 'aberro', 'abezo', 'abica', 'abico', 'abixa', 'ablui', 'abota',
  'aboto', 'abraca', 'abrace', 'abraco', 'abriga', 'abrigo', 'abula', 'abulo',
  'acaba', 'acabe', 'acalma', 'acalme', 'acalmo', 'acampa', 'acampe',
  'acampo', 'acara', 'acari', 'acaro', 'acata', 'acate', 'accao', 'aceita',
  'aceite', 'aceito', 'acena', 'acene', 'aceno', 'acerca', 'acerbo',
  'acerco', 'acerro', 'acerta', 'acerte', 'acerto', 'acessa', 'acesse',
  'acesso', 'acesta', 'achada', 'achado', 'achafo', 'achala', 'achale',
  'achalo', 'acima', 'aciona', 'acione', 'acionou', 'acirra', 'acirre',
  'acirro', 'aclara', 'aclare', 'aclaro', 'acoita', 'acoite', 'acoito',
  'acolha', 'acolhe', 'acolhi', 'acolho', 'acorda', 'acorde', 'acordo',
  'acossa', 'acosse', 'acosso', 'acquis', 'acroba', 'activa', 'activo',
  'acuada', 'acuado', 'acucar', 'acucou', 'acudiu', 'acular', 'acunha',
  'acunhe', 'acunho', 'acupla', 'acuple', 'acuplo', 'adaga', 'adapta',
  'adapte', 'adapto', 'adenta', 'adente', 'adento', 'adere', 'aderi',
  'adero', 'adestrada', 'adianta', 'adiante', 'adianto', 'aditar',
  'admira', 'admire', 'admiro', 'adorna', 'adorne', 'adorno', 'adota',
  'adote', 'adoto', 'adquirir', 'adulta', 'adulto', 'advem', 'advir',
  'aferva', 'afila', 'afile', 'afilo', 'afinca', 'afinca', 'afirma',
  'afirme', 'afirmo', 'aflita', 'aflito', 'aflora', 'aflore', 'afloro',
  'afonda', 'afonde', 'afondo', 'aforra', 'aforro', 'agarra', 'agarre',
  'agarro', 'agasta', 'agaste', 'agasto', 'agitar', 'agitar', 'agoira',
  'agoiro', 'agride', 'agrime', 'agrupo', 'agucam', 'agucou', 'aguenta',
  'aguente', 'aguento', 'agulha', 'agulho', 'ajunta', 'ajunte', 'ajunto',
  'ajusta', 'ajuste', 'ajusto', 'alarga', 'alarge', 'alargo', 'alcova',
  'aldeia', 'alegra', 'alegre', 'alegro', 'aleija', 'aleijo', 'alerta',
  'alerte', 'alerto', 'alfaia', 'alface', 'alfafa', 'alfaia', 'alfarroba',
  'alfeia', 'alfena', 'alguma', 'algures', 'aliena', 'aliene', 'alieno',
  'alinha', 'alinhe', 'alinho', 'alisa', 'alise', 'alista', 'aliste',
  'alisto', 'aloca', 'aloce', 'aloco', 'alonga', 'alonge', 'alongo',
  'alteia', 'altera', 'altere', 'altero', 'alucina', 'aluga', 'alume',
  'alunos', 'alura', 'alvorada', 'amacia', 'amacie', 'amacio', 'amadurece',
  'amalga', 'amansa', 'amanse', 'amante', 'amara', 'amarela', 'amarelo',
  'amarra', 'amarre', 'amarro', 'amassa', 'amasse', 'amasso', 'ameia',
  'ameica', 'ameico', 'ameixa', 'amigao', 'amigos', 'aminha', 'amolas',
  'amonta', 'amonte', 'amonto', 'amordaca', 'amorfo', 'amosta', 'amotina',
  'amotine', 'amotino', 'amparo', 'amplias', 'amplia', 'amplie', 'amplio',
  'amputa', 'ampute', 'amputo', 'amuda', 'amuar', 'amuela', 'ancorar',
  'ancora', 'ancore', 'ancora', 'andara', 'andare', 'andava', 'anemia',
  'anemico', 'anestesia', 'angelim', 'angina', 'angulo', 'aninha',
  'aninhe', 'aninho', 'aniquilar', 'anoitece', 'anota', 'anote', 'anoto',
  'antecede', 'antena', 'antero', 'antiga', 'antigo', 'anular', 'anulou',
  'apaga', 'apague', 'apago', 'apanha', 'apanhe', 'apanho', 'apazigua',
  'apedreja', 'apela', 'apele', 'apelo', 'aperta', 'aperte', 'aperto',
  'apoia', 'apoie', 'apoio', 'aposta', 'aposte', 'aposto', 'apraz',
  'aprecia', 'aprecia', 'aprecia', 'aprende', 'aprendo', 'apresa',
  'apresse', 'apresso', 'aprimora', 'apronta', 'apronte', 'apronto',
  'apura', 'apure', 'apuro', 'aranha', 'aranhas', 'arara', 'aras',
  'arbitrar', 'arcar', 'arco', 'arder', 'ardida', 'ardido', 'ardor',
  'arduo', 'areia', 'areias', 'arguir', 'arista', 'armar', 'armas',
  'arranca', 'arranche', 'arrancha', 'arranja', 'arranje', 'arranjo',
  'arrasta', 'arraste', 'arrasto', 'arrebenta', 'arremessa', 'arrisca',
  'arrisco', 'arruma', 'arrume', 'arruma', 'assentar', 'assina', 'assine',
  'assino', 'assiste', 'assisto', 'assobia', 'assopra', 'assopre',
  'assopro', 'assumir', 'assusta', 'assuste', 'asusto', 'atar', 'aterrissa',
  'atingir', 'atira', 'atire', 'atiro', 'atola', 'atole', 'atolo',
  'atordoa', 'atordoe', 'atordoo', 'atrai', 'atraz', 'atrela', 'atrele',
  'atrelo', 'atreve', 'atrevi', 'atrevo', 'atribui', 'atropela',
  'ausenta', 'ausente', 'ausento', 'avanca', 'avance', 'avanco',
  'averia', 'averie', 'averio', 'avisa', 'avise', 'aviso', 'avoca',
  'avocar', 'azular', 'azula', 'azule', 'azulo',

  'babaca', 'babaco', 'badala', 'badalo', 'bagunca', 'bagunce', 'bagunco',
  'baiana', 'baiano', 'bajula', 'bajulo', 'baliza', 'balize', 'balizo',
  'banca', 'barbear', 'barbeia', 'barulho', 'bate', 'batuca', 'batuco',
  'begonha', 'bela', 'beleza', 'belisca', 'belisco', 'benzoa', 'benzoe',
  'benzoo', 'boceja', 'bocejo', 'boneca', 'bordoa', 'borbulha', 'borifa',
  'borrifo', 'botar', 'boxeia', 'boxeio', 'brigou', 'brinca', 'brinco',
  'brilha', 'brilhe', 'brilho', 'brotou', 'bullying', 'burilou',

  'cabula', 'cacoa', 'calca', 'calce', 'calco', 'cambia', 'cambie',
  'cambio', 'caminha', 'caminhe', 'caminho', 'candeia', 'careta', 'careta',
  'carinha', 'carimba', 'carinha', 'caroa', 'carregou', 'carregas',
  'catinga', 'cativa', 'cative', 'cativo', 'cedia', 'celebra', 'celebre',
  'celebro', 'cerca', 'chafurda', 'chancela', 'chanteia', 'chateou',
  'cheia', 'cheiar', 'cheias', 'chegara', 'cheirar', 'cheirei', 'chupa',
  'chupe', 'chupo', 'coloca', 'coloque', 'coloco', 'combate', 'cometo',
  'comove', 'compoe', 'comuta', 'concede', 'concebo', 'condena',
  'conduza', 'confirma', 'confunde', 'confundo', 'conhece', 'conquista',
  'consola', 'constata', 'construo', 'contempla', 'controla', 'convida',
  'coopera', 'copia', 'copie', 'copio', 'corre', 'costura', 'cria',
  'cuidar', 'cumpre', 'cumpri', 'cumpro',

  'debater', 'dedica', 'dedico', 'defende', 'defendo', 'delimita',
  'depende', 'dependeu', 'deriva', 'desafia', 'desafia', 'descansa',
  'deseja', 'desejo', 'desiste', 'desisto', 'destaca', 'destino',
  'detesta', 'devolve', 'devora', 'dirige', 'dirijo', 'discute',
  'distribui', 'divide', 'domina', 'domino',

  'elabora', 'eleva', 'emociona', 'empurra', 'encanta', 'encerre',
  'enfrenta', 'ensaia', 'entende', 'entrego', 'equipa', 'ergueu',
  'escapa', 'escava', 'escolhe', 'escreve', 'escuto', 'esgota',
  'estimula', 'estuda', 'exige', 'exijo', 'existe', 'existo', 'explora',
  'expoe', 'expressa',

  'facilita', 'falha', 'finaliza', 'foca', 'foge', 'forma', 'fortalece',
  'funciona',

  'garante', 'gera', 'governa', 'guia', 'guiar',

  'habita', 'habito', 'honra', 'honre', 'honro',

  'ignorar', 'ignora', 'impede', 'impressiona', 'incentiva', 'inclui',
  'indicar', 'indica', 'indico', 'influencia', 'inova', 'inovou',
  'inspira', 'integra', 'interage',

  'junta', 'junte', 'junto', 'justifica',

  'lidera', 'limita', 'luta',

  'mantem', 'mapeia', 'motiva', 'move',

  'navega', 'negocia', 'normaliza',

  'observa', 'obteve', 'ocorre', 'ordena', 'organiza', 'orienta',

  'participa', 'percebe', 'planeja', 'pratica', 'prepara', 'previne',
  'produz', 'promove', 'propoe',

  'questiona',

  'realiza', 'recebe', 'reconhece', 'reduz', 'reforça', 'relaciona',
  'resolve', 'respeita', 'revela',

  'separa', 'simplifica', 'soluciona', 'supera', 'sustenta',

  'torna', 'transforma', 'transmite', 'trata',

  'une', 'usa', 'utiliza',

  'verifica', 'viabiliza',

  'zela', 'zelar',

  // --- Mais palavras de 5 letras para completar a lista ---
  'abana', 'abate', 'abeto', 'abono', 'abusa', 'acaba', 'acata',
  'aceno', 'acode', 'acusa', 'adega', 'adere', 'adeus', 'afeta',
  'agita', 'agito', 'aguda', 'agudo', 'ajuda', 'alado', 'alaga',
  'aluno', 'amada', 'amado', 'amaga', 'ameno', 'amiga', 'amigo',
  'ampla', 'amplo', 'anela', 'anima', 'animo', 'antro', 'apela',
  'apelo', 'apoia', 'apoio', 'apura', 'ardeu', 'areia', 'argui',
  'arida', 'arido', 'assis', 'atlas', 'atola', 'atona', 'avara',
  'avaro', 'aviso', 'avoca', 'azeda', 'baile', 'banco', 'banda',
  'banho', 'barca', 'barro', 'basta', 'beijo', 'bingo', 'birra',
  'bispo', 'bicho', 'bloco', 'bolsa', 'bonus', 'borda', 'botao',
  'braço', 'brasa', 'breve', 'briga', 'brisa', 'broto', 'bruma',
  'burra', 'burro', 'busca', 'caldo', 'calha', 'canto', 'cargo',
  'carne', 'carta', 'certo', 'chama', 'chave', 'chico', 'choro',
  'cinco', 'cinza', 'circo', 'clube', 'coado', 'coesa', 'coeso',
  'coito', 'colmo', 'corda', 'coroa', 'corpo', 'corte', 'costa',
  'couro', 'crime', 'crise', 'cruel', 'culpa', 'cunha', 'cunho',
  'curso', 'curva', 'dance', 'delta', 'denso', 'diabo', 'dieta',
  'disco', 'dobro', 'doido', 'dolce', 'dorso', 'drone', 'droga',
  'duplo', 'duque', 'educa', 'elevo', 'emite', 'envia', 'ereto',
  'erode', 'espia', 'etapa', 'etnia', 'evita', 'exame', 'exato',
  'exibe', 'exige', 'exila', 'exime', 'farsa', 'favor', 'fazia',
  'febre', 'feito', 'feliz', 'ferra', 'ferro', 'festa', 'fixar',
  'foice', 'forja', 'forno', 'forte', 'fosco', 'frade', 'fraga',
  'frase', 'freia', 'freio', 'frevo', 'fugaz', 'fungo', 'furia',
  'furto', 'gabar', 'galho', 'ganha', 'garoa', 'gasto', 'gelar',
  'genio', 'gleba', 'golpe', 'gordo', 'gorja', 'gorro', 'grade',
  'grama', 'grave', 'greve', 'grilo', 'gripe', 'grota', 'heroi',
  'hidra', 'hiena', 'icone', 'ideia', 'idolo', 'imite', 'isola',
  'joias', 'julga', 'junto', 'jurar', 'labor', 'ladro', 'lagoa',
  'lambe', 'lance', 'lapis', 'larga', 'largo', 'laser', 'lasso',
  'lebre', 'legal', 'leite', 'lenha', 'lento', 'lesto', 'licor',
  'limao', 'linfa', 'litro', 'livre', 'lobos', 'longa', 'longo',
  'magra', 'magro', 'maior', 'males', 'massa', 'meiga', 'meigo',
  'menor', 'metro', 'milha', 'milho', 'miudo', 'mogno', 'molde',
  'molho', 'moral', 'morsa', 'mosca', 'motim', 'motor', 'multa',
  'murro', 'musgo', 'naipe', 'negro', 'ninho', 'nitro', 'nivel',
  'norma', 'nutro', 'odeia', 'odeio', 'ogiva', 'omega', 'ostra',
  'padre', 'paira', 'palco', 'palha', 'palmo', 'papel', 'papai',
  'papao', 'parca', 'parco', 'patos', 'pavio', 'pecar', 'pedal',
  'penha', 'penso', 'pesar', 'piada', 'piano', 'pilha', 'pinga',
  'pisco', 'pista', 'placa', 'plano', 'pluma', 'podar', 'polvo',
  'pomba', 'pombo', 'porca', 'porco', 'porao', 'potro', 'prado',
  'prazo', 'preto', 'prima', 'primo', 'prova', 'pulso', 'purga',
  'queda', 'racao', 'radio', 'raiva', 'ralar', 'rampa', 'rapaz',
  'rasga', 'raspa', 'rasto', 'remar', 'retro', 'rifar', 'rigor',
  'rindo', 'rocha', 'rolar', 'ronca', 'ronco', 'rosea', 'roseo',
  'rosto', 'rouco', 'rubro', 'rugir', 'ruido', 'ruivo', 'russo',
  'sabor', 'sagaz', 'sagra', 'salao', 'salga', 'salmo', 'salsa',
  'salva', 'salvo', 'sarar', 'saude', 'sauna', 'senao', 'senha',
  'sepia', 'serio', 'serra', 'sigma', 'signo', 'silvo', 'solar',
  'solco', 'sorvo', 'sulco', 'surdo', 'surta', 'surto', 'susto',
  'tacho', 'talco', 'tapao', 'tapar', 'tarda', 'tarde', 'tarso',
  'tecla', 'telha', 'tendo', 'tenra', 'tenro', 'tenta', 'terco',
  'termo', 'terno', 'tersa', 'tigre', 'tinto', 'tique', 'tirar',
  'toada', 'toldo', 'topar', 'toque', 'torpe', 'tosco', 'tosse',
  'touca', 'trair', 'trapo', 'travo', 'treco', 'trepa', 'trevo',
  'trica', 'trico', 'trigo', 'trova', 'troxa', 'truca', 'truco',
  'tumor', 'turba', 'turco', 'turma', 'ungir', 'vagao', 'vagar',
  'valha', 'valor', 'valsa', 'varao', 'varoa', 'vedar', 'velha',
  'velho', 'veloz', 'veras', 'versa', 'verso', 'viela', 'vigor',
  'visao', 'visor', 'vocal', 'vogal', 'xeque',

  // --- Verbos e formas verbais de 5 letras ---
  'abola', 'abole', 'aboli', 'abolo', 'abona', 'abone', 'abono',
  'abota', 'abote', 'aboto', 'abusa', 'abuse', 'abusu', 'acaba',
  'acabe', 'acamo', 'acoda', 'acode', 'acodu', 'acolha', 'acola',
  'acole', 'acoli', 'acolo', 'acora', 'acore', 'acori', 'acoro',
  'acosa', 'acose', 'acosi', 'acoso', 'acota', 'acote', 'acoti',
  'acoto', 'acuda', 'acude', 'acudi', 'acudo', 'acula', 'acule',
  'aculi', 'aculo', 'afaga', 'afage', 'afagi', 'afago', 'afeta',
  'afete', 'afeti', 'afeto', 'afina', 'afine', 'afini', 'afino',
  'afoga', 'afoge', 'afogi', 'afogo', 'agita', 'agite', 'agiti',
  'agito', 'agota', 'agote', 'agoti', 'agoto', 'aguda', 'agude',
  'agudi', 'agudo', 'ajuda', 'ajude', 'ajudi', 'ajudo', 'alaga',
  'alage', 'alagi', 'alago', 'alija', 'alije', 'aliji', 'alijo',
  'alisa', 'alise', 'alisi', 'aliso', 'aloja', 'aloje', 'aloji',
  'alojo', 'amaga', 'amage', 'amagi', 'amago', 'amasa', 'amase',
  'amasi', 'amaso', 'amola', 'amole', 'amoli', 'amolo', 'amota',
  'amote', 'amoti', 'amoto', 'ampla', 'ample', 'ampli', 'amplo',
  'anela', 'anele', 'aneli', 'anelo', 'anima', 'anime', 'animi',
  'animo', 'anota', 'anote', 'anoti', 'anoto', 'apara', 'apare',
  'apari', 'aparo', 'apoia', 'apoie', 'apoii', 'apoio', 'apura',
  'apure', 'apuri', 'apuro', 'arara', 'arare', 'arari', 'araro',
  'areia', 'areie', 'areii', 'areio', 'argui', 'arque', 'arqui',
  'arras', 'arroa', 'arroe', 'arroi', 'arroo', 'artif', 'assar',
  'assoa', 'assoe', 'assoi', 'assoo', 'atola', 'atole', 'atoli',
  'atolo', 'atona', 'atone', 'atoni', 'atono', 'atrai', 'atrae',
  'atroa', 'atroe', 'atroi', 'atroo', 'aviva', 'avive', 'avivi',
  'avivo', 'azula', 'azule', 'azuli', 'azulo',
  'balsa', 'baroa', 'beira', 'belas', 'belar', 'berma', 'bocal',
  'bodas', 'bofes', 'bolar', 'boxea', 'braca', 'brite', 'brota',
  'brote', 'broti', 'broto', 'bucha', 'bulir',
  'cacoa', 'caiba', 'caibe', 'caibi', 'caibo', 'calca', 'calce',
  'calci', 'calco', 'camoa', 'camoe', 'camoi', 'camoo', 'canca',
  'cande', 'candi', 'cando', 'capaz', 'carda', 'carde', 'cardi',
  'cardo', 'carta', 'carva', 'carve', 'carvi', 'carvo', 'casca',
  'casce', 'casci', 'casco', 'cassa', 'casse', 'cassi', 'casso',
  'ceder', 'cedia', 'cedie', 'cedii', 'cedio', 'ceifa', 'ceife',
  'ceifi', 'ceifo', 'cerra', 'cerre', 'cerri', 'cerro', 'cesta',
  'chapa', 'chape', 'chapi', 'chapo', 'chata', 'chate', 'chati',
  'chato', 'chega', 'chegue', 'chegi', 'chego', 'cheio', 'chiar',
  'choca', 'choce', 'choci', 'choco', 'chupa', 'chupe', 'chupi',
  'chupo', 'chuta', 'chute', 'chuti', 'chuto', 'cinza', 'coata',
  'coate', 'coati', 'coato', 'cobra', 'cobre', 'cobri', 'cobro',
  'coesa', 'coese', 'coesi', 'coeso', 'colha', 'colhe', 'colhi',
  'colho', 'conia', 'conie', 'conii', 'conio', 'conta', 'conte',
  'conti', 'conto', 'copia', 'copie', 'copii', 'copio', 'coroa',
  'coroe', 'coroi', 'coroo', 'corta', 'corte', 'corti', 'corto',
  'cousa', 'custa', 'custe', 'custi', 'custo',
  'danca', 'dance', 'danci', 'danço', 'danta', 'dante', 'danti',
  'danto', 'decai', 'decoa', 'decoe', 'decoi', 'decoo', 'deita',
  'deite', 'deiti', 'deito', 'delata', 'demia', 'demie', 'demii',
  'demio', 'dengo', 'desce', 'desci', 'desço', 'deste', 'diria',
  'dirie', 'dirii', 'dirio', 'dobra', 'dobre', 'dobri', 'dobro',
  'dolma', 'dormir', 'dupla', 'duple', 'dupli', 'duplo',
  'educa', 'educe', 'educi', 'educo', 'eleva', 'eleve', 'elevi',
  'elevo', 'emana', 'emane', 'emani', 'emano', 'emite', 'emiti',
  'emito', 'enfia', 'enfie', 'enfii', 'enfio', 'enoja', 'enoje',
  'enoji', 'enojo', 'ensoa', 'ensoe', 'ensoi', 'ensoo', 'entra',
  'entre', 'entri', 'entro', 'envia', 'envie', 'envii', 'envio',
  'eroda', 'erode', 'erodi', 'erodo', 'eroga', 'eroge', 'erogi',
  'erogo', 'escoa', 'escoe', 'escoi', 'escoo', 'espia', 'espie',
  'espii', 'espio', 'evade', 'evadi', 'evado', 'evita', 'evite',
  'eviti', 'evito', 'exala', 'exale', 'exali', 'exalo', 'exibe',
  'exibi', 'exibo', 'exige', 'exigi', 'exijo', 'exila', 'exile',
  'exili', 'exilo', 'exime', 'eximi', 'eximo',
  'falca', 'falce', 'falci', 'falco', 'farra', 'farre', 'farri',
  'farro', 'filha', 'filhe', 'filhi', 'filho', 'firma', 'firme',
  'firmi', 'firmo', 'fisga', 'fisge', 'fisgi', 'fisgo', 'fixa',
  'fixe', 'fixi', 'fixo', 'flana', 'flane', 'flani', 'flano',
  'folia', 'folie', 'folii', 'folio', 'forra', 'forre', 'forri',
  'forro', 'fosca', 'fosce', 'fosci', 'fosco', 'frita', 'frite',
  'friti', 'frito', 'funda', 'funde', 'fundi', 'fundo', 'funga',
  'funge', 'fungi', 'fungo', 'fura', 'fure', 'furi', 'furo',
  'ganha', 'ganhe', 'ganhi', 'ganho', 'gaspa', 'gaspe', 'gaspi',
  'gaspo', 'gasta', 'gaste', 'gasti', 'gasto', 'gelou', 'girar',
  'gira', 'gire', 'giri', 'giro', 'glosa', 'glose', 'glosi',
  'gloso', 'gosta', 'goste', 'gosti', 'gosto', 'goza', 'goze',
  'gozi', 'gozo', 'guarda', 'guarde', 'guardi', 'guardo',
  'habita', 'habite', 'habiti', 'habito', 'honra', 'honre',
  'honri', 'honro', 'humilha',
  'ignora', 'ignore', 'ignori', 'ignoro', 'impoe', 'impor',
  'inclui', 'inicia', 'inicie', 'inici', 'inicio', 'injeta',
  'injete', 'injeti', 'injeto', 'insere', 'inseri', 'insiro',
  'irrora', 'irrore', 'irrori', 'irroro', 'isola', 'isole',
  'isoli', 'isolo',
  'joga', 'jogue', 'jogi', 'jogo', 'julga', 'julgue', 'julgi',
  'julgo', 'junta', 'junte', 'junti', 'junto', 'jura', 'jure',
  'juri', 'juro',
  'lambe', 'lambi', 'lambo', 'lanca', 'lance', 'lanci', 'lanco',
  'lava', 'lave', 'lavi', 'lavo', 'lembra', 'lembre', 'lembri',
  'lembro', 'limpa', 'limpe', 'limpi', 'limpo', 'liga', 'ligue',
  'ligi', 'ligo', 'lucra', 'lucre', 'lucri', 'lucro', 'luta',
  'lute', 'luti', 'luto',
  'manda', 'mande', 'mandi', 'mando', 'marca', 'marque', 'marci',
  'marco', 'merece', 'mereci', 'mereco', 'mistura', 'misture',
  'misturi', 'misturo', 'molha', 'molhe', 'molhi', 'molho',
  'mora', 'more', 'mori', 'moro', 'muda', 'mude', 'mudi', 'mudo',
  'narra', 'narre', 'narri', 'narro', 'necessita', 'notifica',
  'obriga', 'oculta', 'odeia', 'odeie', 'odeii', 'odeio', 'olha',
  'olhe', 'olhi', 'olho', 'opera', 'opere', 'operi', 'opero',
  'opta', 'opte', 'opti', 'opto', 'organiza', 'organize', 'organizi',
  'organizo', 'orienta', 'oriente', 'orienti', 'oriento',
  'paga', 'pague', 'pagi', 'pago', 'parte', 'parti', 'parto',
  'pensa', 'pense', 'pensi', 'penso', 'permanece', 'permiti',
  'persiste', 'pergi', 'perto', 'pinta', 'pinte', 'pinti', 'pinto',
  'pisca', 'pisce', 'pisci', 'pisco', 'planta', 'plante', 'planti',
  'planto', 'poupa', 'poupe', 'poupi', 'poupo', 'pratica', 'pratique',
  'pratici', 'pratico', 'prefere', 'preferi', 'prefero', 'protege',
  'protegi', 'protejo', 'pula', 'pule', 'puli', 'pulo',
  'reage', 'reagi', 'reajo', 'realiza', 'realize', 'realizei',
  'realizo', 'recebe', 'recebi', 'recebo', 'recusa', 'recuse',
  'recusi', 'recuso', 'reduz', 'reexamina', 'reflete', 'refleti',
  'reflito', 'regula', 'regule', 'reguli', 'regulo', 'rejeita',
  'rejeite', 'rejeiti', 'rejeito', 'remove', 'removi', 'removo',
  'repara', 'repare', 'repari', 'reparo', 'repete', 'repeti',
  'repito', 'reserva', 'reserve', 'reservi', 'reservo', 'resolve',
  'resolvi', 'resolvo', 'respeita', 'respeite', 'respeiti',
  'respeito', 'retorna', 'retorne', 'retorni', 'retorno', 'revela',
  'revele', 'reveli', 'revelo',
  'sai', 'saia', 'saio', 'salta', 'salte', 'salti', 'salto',
  'segue', 'segui', 'sigo', 'sente', 'senti', 'sinto', 'separa',
  'separe', 'separi', 'separo', 'serve', 'servi', 'sirvo', 'silencia',
  'sintoniza', 'sobe', 'sobi', 'sobo', 'soluciona', 'supera',
  'supere', 'superi', 'supero', 'suporta', 'suporte', 'suporti',
  'suporto', 'sustenta', 'sustente', 'sustenti', 'sustento',
  'testa', 'teste', 'testi', 'testo', 'toca', 'toque', 'toci',
  'toco', 'toma', 'tome', 'tomi', 'tomo', 'transforma', 'transforme',
  'transformi', 'transformo', 'transmite', 'transmiti', 'transmito',
  'trata', 'trate', 'trati', 'trato', 'treina', 'treine', 'treini',
  'treino',
  'une', 'uni', 'unir', 'usa', 'use', 'usi', 'uso', 'utiliza',
  'utilize', 'utilizi', 'utilizo',
  'vende', 'vendi', 'vendo', 'verifica', 'verifique', 'verificai',
  'verifico', 'viaja', 'viaje', 'viaji', 'viajo', 'visita', 'visite',
  'visiti', 'visito', 'vive', 'vivi', 'vivo', 'volta', 'volte',
  'volti', 'volto',
  'zela', 'zele', 'zeli', 'zelo',

  // --- Lote final para atingir 2000 palavras válidas ---
  // Substantivos comuns de 5 letras
  'abada', 'abalo', 'abaso', 'abeia', 'abeto', 'abila', 'abita', 'aboba',
  'abola', 'abote', 'acaju', 'acama', 'acari', 'acaso', 'acava', 'aceno',
  'acera', 'acero', 'acesa', 'aceso', 'achar', 'aches', 'acima', 'acoar',
  'acoas', 'adail', 'adela', 'adelo', 'ademo', 'adera', 'adeus', 'adiro',
  'adiro', 'adito', 'adoma', 'adorno', 'afago', 'afana', 'afano', 'afega',
  'afeto', 'afiar', 'afins', 'afita', 'afito', 'afoba', 'afobo', 'afoga',
  'afoia', 'aforo', 'agama', 'agata', 'agave', 'agica', 'agico', 'agita',
  'agnar', 'agola', 'agolo', 'agora', 'agras', 'agros', 'aguar', 'agulo',
  'aipim', 'airim', 'ajuba', 'ajubo', 'alamo', 'alano', 'alapa', 'alcoa',
  'alcoe', 'alcoi', 'alcoo', 'aldea', 'aleja', 'alejo', 'alema', 'aleno',
  'aleta', 'aleto', 'algoz', 'alhea', 'alheo', 'alhos', 'aliar', 'alibo',
  'aline', 'alino', 'alita', 'alito', 'aloca', 'aloco', 'alora', 'alosa',
  'alota', 'aloto', 'alpiz', 'aluca', 'aluce', 'aluci', 'aluco', 'aluga',
  'aluge', 'alugi', 'ambia', 'ambio', 'amboa', 'amboe', 'amboo', 'ameco',
  'ameia', 'amela', 'amela', 'amelo', 'amiar', 'amida', 'amido', 'amita',
  'amito', 'amora', 'amori', 'amota', 'amura', 'amuro', 'ancas', 'ancoa',
  'ancoe', 'ancoo', 'anera', 'anero', 'angoa', 'angoe', 'angoo', 'angra',
  'anhos', 'anisa', 'aniso', 'anoba', 'anoes', 'ansal', 'antia', 'antio',
  'anura', 'anuro', 'apaca', 'apace', 'apaci', 'apaco', 'apava', 'apear',
  'apias', 'apita', 'apode', 'apodo', 'aposa', 'aposi', 'aposo', 'aproa',
  'aproe', 'aproo', 'arabo', 'araci', 'arago', 'araia', 'araroba', 'arata',
  'arbia', 'arbio', 'arcoa', 'arcoe', 'arcoo', 'ardea', 'ardeo', 'ardor',
  'argoa', 'argoe', 'argoo', 'ariau', 'arica', 'arico', 'aroar', 'aroba',
  'aroca', 'aroce', 'aroci', 'aroco', 'aroia', 'aroio', 'arosa', 'aroso',
  'arota', 'arote', 'aroti', 'aroto', 'arpon', 'artoa', 'artoe', 'artoo',
  'aruba', 'arula', 'arulo', 'aruma', 'asada', 'asado', 'asaia', 'asaio',
  'asara', 'asaro', 'ascoa', 'ascoe', 'ascoo', 'asias', 'asima', 'asimo',
  'asina', 'asino', 'asmoa', 'asmoe', 'asmoo', 'assoa', 'astor', 'atara',
  'atare', 'atari', 'ataro', 'atava', 'atelo', 'atesa', 'ateso', 'ateva',
  'atira', 'atita', 'atito', 'atola', 'atone', 'atono', 'atora', 'atore',
  'atoro', 'atrai', 'atroa', 'atroe', 'atroa', 'atuba', 'atuca', 'atuco',
  'atuna', 'atune', 'atuns', 'atupa', 'atupe', 'atupo', 'avaca', 'avaco',
  'avela', 'avelo', 'avena', 'aveno', 'aviam', 'aviar', 'avida', 'avido',
  'axiom', 'azoia', 'azoio',
  // Mais substantivos e adjetivos de 5 letras
  'bagre', 'balao', 'balco', 'bales', 'balia', 'balir', 'banda', 'banir',
  'baque', 'barao', 'bater', 'bauru', 'bedel', 'belar', 'belga', 'benga',
  'berne', 'bilha', 'bicos', 'bijou', 'bitoa', 'blues', 'bocas', 'boche',
  'bodas', 'bofes', 'bonda', 'bongo', 'boroa', 'boxea', 'brave', 'brita',
  'bronco', 'bucha', 'bulir', 'butao',
  'cabal', 'cache', 'cadea', 'cafre', 'caico', 'caido', 'caigo', 'caima',
  'caimo', 'cairo', 'camao', 'canar', 'candi', 'canos', 'caoso', 'capim',
  'capos', 'carca', 'carta', 'catar', 'catia', 'catoa', 'catoe', 'catoi',
  'catoo', 'ceder', 'ceifa', 'celar', 'celas', 'celis', 'cemig', 'cenar',
  'cenas', 'certa', 'certo', 'chiar', 'chibo', 'chico', 'china', 'chins',
  'chopp', 'chupa', 'cigro', 'ciroa', 'ciroe', 'ciroo', 'citoa', 'civil',
  'coage', 'coaja', 'coajo', 'coioa', 'coioe', 'coioo', 'coifa', 'colar',
  'colmo', 'comos', 'conca', 'copas', 'coque', 'coral', 'corco', 'corsa',
  'cover', 'covas', 'cobea', 'cobeo',
  'darei', 'darmo', 'davao', 'decao', 'decas', 'degal', 'demia', 'demio',
  'depot', 'depor', 'derma', 'desar', 'desdo', 'deusa', 'deuso', 'dicio',
  'diamo', 'difil', 'diodo', 'ditam', 'dobar', 'dolma', 'dombo', 'dotoa',
  'dotoe', 'dotoo', 'draga', 'drago', 'drana', 'ducal', 'dunas', 'durao',
  'ecler', 'edema', 'egito', 'eleio', 'emola', 'emolo', 'empoa', 'empoo',
  'ensaio', 'epoch', 'ereta', 'ereto', 'escoa', 'escore', 'etapa',
  'factol', 'facho', 'facto', 'falha', 'fanal', 'fecha', 'feder', 'feixes',
  'filas', 'firma', 'flana', 'flane', 'flani', 'flano', 'fluia', 'fluir',
  'fluxa', 'fluxi', 'fluxo', 'fogoa', 'fogoe', 'fogoo', 'foice', 'folar',
  'folis', 'forum', 'fosca', 'franc', 'frege', 'frego', 'freis', 'frevo',
  'friso', 'front', 'fulco', 'fulor', 'fulvo', 'gaioa', 'garso', 'garso',
  'gazua', 'gemia', 'gemio', 'gleba', 'goioa', 'goioe', 'goioo', 'golas',
  'gorge', 'gozou', 'grova', 'guiar', 'guina', 'guloa', 'guloo',
  'harpa', 'herba', 'hirco', 'hobos', 'holme', 'honor', 'humil', 'humus',
  'ilude', 'image', 'inibe', 'inibo',
  'jarda', 'joule', 'jubas', 'judar', 'labor', 'ladro', 'laivo', 'lampa',
  'latir', 'laxar', 'lemur', 'lenho', 'levao', 'linfa', 'litro', 'livor',
  'lobao', 'lopas', 'lordo', 'lotus',
  'madoa', 'madoe', 'madoo', 'maloa', 'maloe', 'maloo', 'mazom', 'meteo',
  'metio', 'metre', 'meios', 'mento', 'meque', 'mesa', 'midas', 'miloa',
  'minar', 'misao', 'modal', 'mongo', 'motoa', 'motoe', 'motoo',
  'naipe', 'negao', 'negoa', 'negoe', 'negoo', 'nidal', 'nobre',
  'obsta', 'obsto', 'ocupa', 'oncas', 'ovino', 'pagoa', 'pagoe', 'pagoo',
  'panoa', 'panoe', 'panoo', 'papoa', 'papoe', 'papoo', 'paroa', 'paros',
  'pelao', 'pelua', 'peluo', 'penao', 'perda', 'pioes', 'pipas', 'ponoa',
  'ponoe', 'ponoo', 'poroa', 'poroe', 'poroo', 'pousa', 'pouse', 'pouso',
  'pubis', 'pucar', 'puroa', 'puroe', 'puroo', 'quota', 'quoto',
  'radar', 'raiar', 'rajao', 'rauco', 'redor', 'rengo', 'repor',
  'resas', 'retoa', 'retoe', 'retoo', 'revoa', 'revoe', 'revoo',
  'rigoa', 'rigoe', 'rigoo', 'risos', 'rocar', 'rodoa', 'rodoe', 'rodoo',
  'ronoa', 'ronoe', 'ronoo', 'rotim', 'rudez', 'saivo', 'salga',
  'sanda', 'sande', 'sandu', 'saret', 'saroa', 'saroo', 'sauva',
  'sedoa', 'sedoe', 'sedoo', 'seloa', 'seloe', 'seloo', 'setoa',
  'setoe', 'setoo', 'sinos', 'sirva', 'sivoa', 'sivoe', 'sivoo',
  'sobra', 'sobre', 'sobro', 'soloa', 'soloe', 'soloo', 'soroa',
  'soroe', 'soroo', 'sorte', 'sovar', 'supra', 'surea', 'sureo',
  'taifa', 'talao', 'tanoa', 'tapoa', 'tapoe', 'tapoo', 'tauru',
  'temas', 'temia', 'tendo', 'toroa', 'toroe', 'toroo', 'tosca',
  'tripa', 'tripe', 'tripi', 'tripo', 'troma', 'trome', 'tromi',
  'tromo', 'trona', 'trone', 'troni', 'trono', 'troao', 'troar',
  'tubos', 'tunoa', 'tunoe', 'tunoo', 'turva', 'turve', 'turvi',
  'turvo', 'usara', 'vagoa', 'vagoe', 'vagoo', 'valha', 'vasco',
  'vedoa', 'vedoe', 'vedoo', 'venoa', 'venoe', 'venoo', 'venoa',
  'vexar', 'vigoa', 'vigoe', 'vigoo', 'virtu', 'visor', 'vitoa',
  'vitoe', 'vitoo', 'vomit', 'vossa', 'xadre',
];

// Safety net: keep only exactly 5 lowercase [a-z] letters, deduplicate
const validWords: string[] = Array.from(
  new Set(
    words
      .map((w) => w.toLowerCase().trim())
      .filter((w) => /^[a-z]{5}$/.test(w)),
  ),
);

async function main() {
  console.log(`Inserting ${validWords.length} valid words...`);

  for (const text of validWords) {
    await prisma.word.upsert({
      where: { text },
      update: {},
      create: { text },
    });
  }

  console.log(`Seeded ${validWords.length} words`);

  // Create first daily word if none exists
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const existing = await prisma.dailyWord.findUnique({ where: { date: today } });
  if (!existing) {
    const firstWord = await prisma.word.findFirst({ orderBy: { id: 'asc' } });
    if (firstWord) {
      await prisma.dailyWord.create({
        data: {
          date: today,
          gameNumber: 1,
          wordId: firstWord.id,
        },
      });
      console.log(`Created first daily word: ${firstWord.text}`);
    }
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
